apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: default
  labels:
    app: frontend-app
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - name: frontend-port
      port: 80
      targetPort: 80
      nodePort: 30010 # Choose a port number that is available in your cluster
