apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: app-urls-configmap
      containers:
        - name: frontend-app
          image: alexdecb/video-drom-front:latest 
          ports:
            - containerPort: 80  
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/app_urls.json
              subPath: app_urls.json