apiVersion: v1
kind: Service
metadata:
  name: vue-nodeport
  namespace: default
  labels:
    app: vue-app
spec:
  type: NodePort
  selector:
    app: vue-app
  ports:
    - name: spring-port
      port: 80
      targetPort: 80
      nodePort: 30010 # Choose a port number that is available in your cluster
