apiVersion: v1
kind: Service
metadata:
  name: mariadb-nodeport
  namespace: default
  labels:
    app: mariadb
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - name: mariadb-port
      port: 3306
      targetPort: 3306
      nodePort: 30001 # Choose a port number that is available in your cluster
