apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: default
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: nginx-port
      port: 30208
      targetPort: 80
      nodePort: 30005 # Choose a port number that is available in your cluster
