apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: video-files
              mountPath: /video_server/
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf-configmap
        - name: video-files
          persistentVolumeClaim:
            claimName: video-files
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
