apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: video-server-sts
spec:
  selector:
    matchLabels:
      app: video-server
  replicas: 1
  template:
    metadata:
      labels:
        app: video-server
    spec:
      containers:
        - name: video-server
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: video-files
              mountPath: /video_server/
      volumes:
        - name: nginx-conf
          configMap:
            name: video-server-cm
        - name: video-files
          persistentVolumeClaim:
            claimName: video-files
---
apiVersion: v1
kind: Service
metadata:
  name: video-server-service
spec:
  selector:
    app: video-server
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
