apiVersion: v1
kind: Service
metadata:
  name: video-server-nodeport
  namespace: default
  labels:
    app: video-server
spec:
  type: NodePort
  selector:
    app: video-server
  ports:
    - name: video-server-port
      port: 80
      targetPort: 80
      nodePort: 30005 # Choose a port number that is available in your cluster
