apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-server-deploy
spec:
  selector:
    matchLabels:
      app: video-server
  replicas: 1
  template:
    metadata:
      labels:
        app: video-server
    spec:
      containers:
        - name: video-server
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nfs-volume
              mountPath: /video_server/
      volumes:
        - name: nginx-conf
          configMap:
            name: video-server-cm
        - name: nfs-volume
          nfs: 
            # URL for the NFS server
            server: 10.152.183.39
            path: /
