apiVersion: batch/v1
kind: Deployment
metadata:
  name: mpd-generator
spec:
  template:
    spec:
      containers:
      - name: mpd-generator
        image: alexdecb/mpd-generator:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: video-files-volume
          mountPath: /tmp/workdir/dash_videos
      restartPolicy: Never
      volumes:
      - name: video-files-volume
        persistentVolumeClaim:
          claimName: video-files
