apiVersion: batch/v1
kind: Job
metadata:
  name: generate-mpds
spec:
  template:
    spec:
      containers:
      - name: generate-mpds
        image: alexdecb/generate_mpds:3
        imagePullPolicy: Always
        volumeMounts:
        - name: video-files-volume
          mountPath: /tmp/workdir/dash_videos
      restartPolicy: Never
      volumes:
      - name: video-files-volume
        persistentVolumeClaim:
          claimName: video-files
