apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpd-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpd-generator
  template:
    metadata:
      labels:
        app: mpd-generator
    spec:
      containers:
      - name: mpd-generator
        image: alexdecb/mpd-generator:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: nfs-volume
          mountPath: /usr/src/app/dash_videos
      volumes:
      - name: nfs-volume
        nfs: 
          # URL for the NFS server
          server: 10.152.183.39
          path: /
