apiVersion: v1
kind: Service
metadata:
  name: mpd-generator-service
spec:
  selector:
    app: mpd-generator 
  ports:
  - protocol: TCP
    port: 80  # Port within the cluster to access the service
    targetPort: 8083  # Port the container is listening on


