apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  namespace: default
  labels:
    app: backend-app
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - name: backend-port
      port: 8081
      targetPort: 8081
      nodePort: 30002 
