apiVersion: v1
kind: Service
metadata:
  name: spring-nodeport
  namespace: default
  labels:
    app: spring-app
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - name: spring-port
      port: 8081
      targetPort: 8081
      nodePort: 30002 # Choose a port number that is available in your cluster
